osx_image: xcode10.2
language: objective-c
env:
  matrix:
    - PLATFORM=iOS SDK=iphonesimulator SCHEME=SocketLogger-iOS DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=10.0"
    - PLATFORM=Mac SDK=macosx SCHEME=SocketLogger-Mac DESTINATION="platform=macOS"
    - PLATFORM=tvOS SDK=appletvsimulator SCHEME=SocketLogger-tvOS DESTINATION="platform=tvOS Simulator,name=Apple TV 1080p,OS=10.0"
install: 
  - brew remove swiftlint --force || true
  - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/ad61dfd/Formula/swiftlint.rb
  - brew remove carthage --force || true
  - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/ad61dfd/Formula/carthage.rb
  - gem install xcpretty
  - carthage bootstrap --platform "$PLATFORM" --cache-builds
script:
  - Scripts/test
cache:
  directories:
    - Carthage/Build
